steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-crud-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-crud-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-crud-app', '--image', 'gcr.io/$PROJECT_ID/my-crud-app', '--platform', 'managed', '--region', 'europe-west2', '--add-cloudsql-instances', 'your-project-id:europe-west2:flask-crud-instance']
images:
  - 'gcr.io/$PROJECT_ID/my-crud-app'
options:
  logging: CLOUD_LOGGING_ONLY
